config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/bands')

  resources :users, only: [:create, :new, :show]
  resource :session, only: [:show, :create, :new, :destroy]

  resources :bands

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, :tracks, only: [:create, :new, :edit, :show, :update, :destroy]

  resources :albums, only: [:create, :destroy, :edit, :show, :update] do
    resources :tracks, only: [:new]
  end
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  live       :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  band_id    :integer          not null
#

class Album < ActiveRecord::Base
  validates :title, :live, :band_id, presence: true

  belongs_to :band
  has_many :tracks

  attr_reader :display_title

  def display_title
    title = self.title.to_s
    title += " (Live)" if self.live

    title
  end
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums

  has_many :tracks,
    through: :albums
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  bonus      :boolean          default(FALSE), not null
#  lyrics     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  album_id   :integer          not null
#

class Track < ActiveRecord::Base
  validates :name, :bonus, :album_id, presence: true

  belongs_to :album

  has_one :band,
    through: :album
  end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :email, :session_token, uniqueness: true, presence: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password
  after_initialize :ensure_session_token

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(options)
    possible_user = User.find_by_email(options[:email])
    return ["Email address not found!"] if possible_user.nil?

    possible_user.is_password?(options[:password]) ? possible_user : ["Incorrect password!"]
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password

    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    digest_bcrypt_object = BCrypt::Password.new(self.password_digest)

    digest_bcrypt_object.is_password?(password)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_login

  def new
    if params[:band_id]
      @band = Band.find(params[:band_id])
      @album = Album.new(band_id: @band.id)
    else
      @album = Album.new
    end

    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages

      render :new
    end
  end

  def show
    @album = Album.find(params[:id])

    render :show
  end

  def edit
    @album = Album.find(params[:id])

    render :edit
  end

  def update
    album = Album.find(params[:id])
    album.update(album_params)

    redirect_to album_url(album)
  end

  def destroy
    album = Album.find(params[:id])
    band = album.band

    album.destroy

    redirect_to band_url(band)
  end

  private
  def album_params
    params.require(:album).permit(:title, :live, :band_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def logged_in?
    !current_user.nil?
  end

  def current_user
    return nil if session[:session_token].nil?

    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout_user!
    current_user.reset_session_token!

    session[:session_token] = nil
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

  def require_login
    redirect_to session_url unless logged_in?
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_login

  def index
  end

  def new
    @band = Band.new

    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages

      render :new
    end
  end

  def show
    @band = Band.find(params[:id])

    render :show
  end

  def edit
    @band = Band.find(params[:id])

    render :edit
  end

  def update
    band = Band.find(params[:id])
    band.update(band_params)

    redirect_to band_url(band)
  end

  def destroy
    Band.find(params[:id]).destroy

    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def show
  end

  def new
    @user = User.new

    render :new
  end

  def create
    search_result = User.find_by_credentials(user_params)

    if search_result.is_a?(User)
      user = search_result
      login_user!(user)

      redirect_to user_url(user)
    else
      @user = User.new(user_params)
      flash.now[:errors] = search_result

      render :new
    end
  end

  def destroy
    logout_user!

    redirect_to new_session_url
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_login

  def new
  end

  def create
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new

    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user!(@user)

      redirect_to user_url(@user.id)
    else
      flash.now[:errors] = @user.errors.full_messages

      render :new
    end
  end

  def show
    @user = User.find(params[:id])

    if current_user && @user.id == current_user.id
      render :profile_page
    else
      render :forbidden
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<% url = album.persisted? ? album_url(album) : albums_url %>
<% method = album.persisted? ? "PATCH" : "POST" %>

<h2><font color="emerald"><%= album.title ? album.title : "Add an album" %></font></h2>

<form action="<%= url %>"
      method="POST">

  <input type="hidden"
         name="_method"
         value="<%= method %>">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <font color="green">
  <label for="albums_band">Band:</label>
  <select id="albums_band"
          name="album[band_id]">
      <option value=nil <%= "selected" if album.band_id.nil? %>""</option>
    <% Band.all.each do |band| %>
      <option value="<%= band.id %>"
      <%= "selected" if band.id == album.band_id %>>
        <%= band.name %>
      </option>
    <% end %>
  </select>
  </font>

  <br><br>

  <font color="emerald">
  <label for="album_title">Album title:</label>
  <input id="album_title"
         type="text"
         name="album[title]"
         value="<%= album.title %>">
  </font>

  <br><br>

  <font color="blue">
  <label for="live">Live</label>
  <input id="live"
         type="radio"
         name="album[live]"
         value="true"
         <%= "checked" if album.live %>>

  <label for="studio">Studio</label>
  <input id="studio"
         type="radio"
         name="album[live]"
         value="false"
         <%= "checked" if !album.live %>>
  </font>

  <br><br>

  <input type="submit"
         value="<%= album.title ? "Update!" : "Add album!" %>">
</form>

<br>

<% method = album.band_id.nil? ? bands_url : band_url(album.band_id) %>
<%= button_to "Cancel", method , method: :get %>

app/views/albums/edit.html.erb
<%= render "shared/errors" %>

<%= render "form", album: @album %>

app/views/albums/new.html.erb
<%= render "shared/errors" %>

<%= render "form", album: @album %>

app/views/albums/show.html.erb
<br>

<%= link_to "<< Back to all bands", bands_url %>

<br><br>

<%= link_to "<< Back to #{@album.band.name}", band_url(@album.band) %>

<h2><font color="emerald">
  <%= @album.band.name %> -
  <%= @album.display_title %>
</font> <font size=2>
  <%= link_to "(edit album)", edit_album_url %>
</font></h2>

<h3><font color="green">Tracks:</font></h3>
<ul>
  <% @album.tracks.each do |track| %>
    <li><%= link_to "#{track.name}", track_url(track) %></li>
  <% end %>
</ul>

<br>

<%= button_to "Add track", new_track_url, method: :get %>

<br><br>

<%= button_to "Delete album O.O", album_url(@album), method: :delete %>

app/views/bands/_form.html.erb
<% url = band.persisted? ? band_url(band) : bands_url %>
<% method = band.persisted? ? "PATCH" : "POST" %>

<h2><font color="emerald"><%= band.name ? band.name : "Add a band" %></font></h2>

<form action="<%= url %>"
      method="POST">

  <input type="hidden"
         name="_method"
         value="<%= method %>">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="band_name"><font color="emerald">Band name:</font></label>
  <input id="band_name"
         type="text"
         name="band[name]"
         value="<%= band.name %>">

  <input type="submit"
         value="<%= band.name ? "Update!" : "Add band!" %>">

</form>

<br>

<%= button_to "Cancel", bands_url, method: :get %>

app/views/bands/edit.html.erb
<%= render "shared/errors" %>

<%= render "form", band: @band %>

app/views/bands/index.html.erb
<a name="all_bands"/>
<h2><font color="emerald">All Bands</font></h2>

<ul>
  <% Band.all.each do |band| %>
    <li><%= link_to band.name, band_url(band) %></li>
  <% end %>
</ul>

<br>

<%= button_to "Add a band", new_band_url, method: :get %>

<br>

<a name="all_albums"/>
<h2><font color="green">All Albums</font></h2>

<ul>
  <% Album.all.each do |album| %>
    <li><%= link_to album.display_title, album_url(album) %> by <%= link_to album.band.name, band_url(album.band) %></li>
  <% end %>
</ul>

<br>

<%= button_to "Add an album", new_album_url, method: :get %>

app/views/bands/new.html.erb
<%= render "shared/errors" %>

<%= render "form", band: @band %>

app/views/bands/show.html.erb
<br>
<%= link_to "<< Back to all bands", bands_url %>

<h2><font color="emerald"><%= @band.name %></font> <font size=2><%= link_to "(edit)", edit_band_url %></font></h2>

<h3><font color="green">Albums:</font></h3>
<ul>
  <% @band.albums.each do |album| %>
    <li>
      <%= link_to album.display_title, album_url(album) %>
    </li>
  <% end %>
</ul>

<br>

<%= button_to "Add album", new_band_album_url(@band), method: :get %>

<br><br>

<%= button_to "Delete band O.O", band_url(@band), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>♪ ♫ ♪ ♫ Welcome to MusicApp! ♫ ♪ ♫ ♪</h1>

<%= render "shared/login_status_buttons" %>

<%= yield %>

</body>
<footer>
  <br>
  <font color="silver" size=1>
    __________________________ <br>
    &nbsp;&nbsp;&nbsp;&nbsp;
    2016 - Elizabeth Sparks
  </font>
</footer>
</html>

app/views/shared/_email_and_password_form.html.erb
<% title = (action == session_url ? "Log in" : "Sign up for a new account!") %>

<h2><%= title %></h2>

<form action="<%= action %>"
      method="POST">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="email">Email address: </label>
  <input id="email"
         type="text"
         name="user[email]"
         value="<%= user.email %>">

  <label for="password">Password: </label>
  <input id="password"
         type="password"
         name="user[password]"
         value="<%= user.password %>">

  <input type="submit"
         value="<%= action == session_url ? "Log me in!" : "Sign up!" %>">
</form>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <p><font color="red"><%= error %></font></p>
  <% end %>
<% end %>

app/views/shared/_login_status_buttons.html.erb
<font color="gray">
  <% case request.original_url %>
  <% when session_url, new_session_url, new_user_url %>
  <% else %>
    <% if current_user %>
      <label>
        Logged in as: <%= current_user.email %>
        <%= button_to "log out", session_url, method: :delete %>

        <%= button_to "my profile", user_url(current_user.id), method: :get unless request.original_url == user_url(current_user.id) %>
      </label>
    <% else %>
      <%= button_to "log in", new_session_url, method: :get %>
      <%= button_to "sign up", new_user_url, method: :get %>
    <% end %>
  <% end %>
</font>

app/views/users/_name_and_email.html.erb
<form action="<%= users_url %>" method="POST">

  <label for="email">Email address: </label>
  <input id="email"
         type="text"
         name="user[email]"
         value="<%= @user.email %>"
         >

  <label for="password">Password: </label>
  <input id="password"
         type="password"
         name="user[password]"
         value="<%= @user.password %>"
         >

  <input type="submit" value="Sign up!">
</form>

app/views/users/forbidden.html.erb
<h2>You do not have access to this page!</h2>

app/views/users/new.html.erb
<%= render "shared/email_and_password_form", user: @user, action: users_url %>

<%= render "shared/errors" %>

<p><%= link_to "<< Back", session_url %></p>

app/views/users/profile_page.html.erb
<h2>Welcome back, <%= @user.email %>!</h2>


<%= link_to "<< Main", bands_url %>
<%= link_to "Go to Bands", "#{bands_url}#all_bands" %>
<%= link_to "Go to Albums", "#{bands_url}#all_albums" %>